# Copyright (c) 2017 Alexandre Roman <alexandre.roman@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM sdhibit/rpi-raspbian:jessie
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends build-essential git
RUN apt-get install -y --no-install-recommends autopoint debhelper dh-autoreconf gcc libavutil-dev libavcodec-dev libavformat-dev libjpeg-dev libsqlite3-dev libexif-dev libid3tag0-dev libogg-dev libvorbis-dev libflac-dev

RUN git clone http://git.code.sf.net/p/minidlna/git minidlna-git
WORKDIR /minidlna-git
RUN git checkout v1_2_0

RUN ./autogen.sh && ./configure && make

CMD echo Binary built in /minidlna-git
